### ISSUE TITLE
KeyError: 'normed_feature' not found

### ISSUE THREAD

**Issue by rohanchandra30** [zlmzju/part_reid#10]
In the extract_features method in the Extractor() class, there is a line:

`normed_features=self.net.blobs['normed_feature'].data.copy()`

I checked the _caffe.cpp file in ./caffe/python/caffe/_caffe.cpp and I then checked all the properties for net.blobs and 'normed_feature' was not one of them.

Any ideas on how to resolve this?

Thanks

**Comment by zlmzju** [comment]
The key of normed_feature is the blob name defined in network architecture. You can find it in 'models/demo/test.prototxt'.

**Comment by zlmzju** [comment]
The key of normed_feature is the blob name defined in network architecture. You can find it in 'models/demo/test.prototxt'.
