### ISSUE TITLE
about data layer

### ISSUE THREAD

**Issue by zw-shen** [zlmzju/part_reid#5]
Firstly, thanks your great work!
but  i cannot use your python layer to train my model. it will stop when cv2 reading one image. 
could you give me some help about this?
thanks

**Comment by ittefaq11** [comment]
Were you able to resolve this and train a model based on this repo ?

**Comment by zlmzju** [comment]
@bea-tree , I guess you are using opencv3 when errors occur in cv2.imread(). You can use opencv2 and I will also work on the compatibility of opencv3.

**Comment by zlmzju** [comment]
@bea-tree , I guess you are using multiple versions of opencv.
Similar errors occur in cv2.imread() when I have different versions of opencv-cpp and opencv-python.
You can resolve the problem by installing the same version of opencv in your system.
