### ISSUE TITLE
train shell script

### ISSUE THREAD

**Issue by ittefaq11** [zlmzju/part_reid#6]
From the readme - it seems that the train.sh script is missing in the train folder. I am looking for if it is possible to get the training script for replicating and improving by tuning hyperparameters.

**Comment by zlmzju** [comment]
The script name was `start.sh`, sorry for the typo. I have changed the file name to `train.sh`.

**Comment by ittefaq11** [comment]
Thanks @zlmzju  for the reply. The train.sh seems to look for run*.sh in $dataset/$expname could not find a relevant folder in you google drive dataset in Market* folder. Also unable to see a run.sh and run_partnet.bat in shell mode. It would be helpful to get info on above to get a training session.

**Comment by zlmzju** [comment]
@ittefaq11 , the `$dataset/$expname/run*.sh` will be generated by running the `train.sh` script.

**Comment by Phoebe-star** [comment]
I  got the error    ""    AttributeError: 'LayerParameter' object has no attribute 'triplet_loss_param' ""
